export const COUNTRY_CODES = [
  { code: '+7', country: 'Abkhazia', flag: 'ge' },
  { code: '+93', country: 'Afghanistan', flag: 'af' },
  { code: '+358', country: 'Åland', flag: 'ax' },
  { code: '+355', country: 'Albania', flag: 'al' },
  { code: '+213', country: 'Algeria', flag: 'dz' },
  { code: '+1', country: 'American Samoa', flag: 'as' },
  { code: '+376', country: 'Andorra', flag: 'ad' },
  { code: '+244', country: 'Angola', flag: 'ao' },
  { code: '+1', country: 'Anguilla', flag: 'ai' },
  { code: '+1', country: 'Antigua and Barbuda', flag: 'ag' },
  { code: '+54', country: 'Argentina', flag: 'ar' },
  { code: '+374', country: 'Armenia', flag: 'am' },
  { code: '+297', country: 'Aruba', flag: 'aw' },
  { code: '+247', country: 'Ascension', flag: 'sh' },
  { code: '+61', country: 'Australia', flag: 'au' },
  { code: '+43', country: 'Austria', flag: 'at' },
  { code: '+994', country: 'Azerbaijan', flag: 'az' },
  { code: '+1', country: 'Bahamas', flag: 'bs' },
  { code: '+973', country: 'Bahrain', flag: 'bh' },
  { code: '+880', country: 'Bangladesh', flag: 'bd' },
  { code: '+1', country: 'Barbados', flag: 'bb' },
  { code: '+375', country: 'Belarus', flag: 'by' },
  { code: '+32', country: 'Belgium', flag: 'be' },
  { code: '+501', country: 'Belize', flag: 'bz' },
  { code: '+229', country: 'Benin', flag: 'bj' },
  { code: '+1', country: 'Bermuda', flag: 'bm' },
  { code: '+975', country: 'Bhutan', flag: 'bt' },
  { code: '+591', country: 'Bolivia', flag: 'bo' },
  { code: '+599', country: 'Bonaire', flag: 'bq' },
  { code: '+387', country: 'Bosnia and Herzegovina', flag: 'ba' },
  { code: '+267', country: 'Botswana', flag: 'bw' },
  { code: '+55', country: 'Brazil', flag: 'br' },
  { code: '+246', country: 'British Indian Ocean Territory', flag: 'io' },
  { code: '+1', country: 'British Virgin Islands', flag: 'vg' },
  { code: '+673', country: 'Brunei Darussalam', flag: 'bn' },
  { code: '+359', country: 'Bulgaria', flag: 'bg' },
  { code: '+226', country: 'Burkina Faso', flag: 'bf' },
  { code: '+257', country: 'Burundi', flag: 'bi' },
  { code: '+855', country: 'Cambodia', flag: 'kh' },
  { code: '+237', country: 'Cameroon', flag: 'cm' },
  { code: '+1', country: 'Canada', flag: 'ca' },
  { code: '+238', country: 'Cape Verde', flag: 'cv' },
  { code: '+599', country: 'Caribbean Netherlands', flag: 'bq' },
  { code: '+1', country: 'Cayman Islands', flag: 'ky' },
  { code: '+236', country: 'Central African Republic', flag: 'cf' },
  { code: '+235', country: 'Chad', flag: 'td' },
  { code: '+56', country: 'Chile', flag: 'cl' },
  { code: '+86', country: 'China', flag: 'cn' },
  { code: '+61', country: 'Christmas Island', flag: 'cx' },
  { code: '+61', country: 'Cocos (Keeling) Islands', flag: 'cc' },
  { code: '+57', country: 'Colombia', flag: 'co' },
  { code: '+269', country: 'Comoros', flag: 'km' },
  { code: '+242', country: 'Congo', flag: 'cg' },
  { code: '+243', country: 'Congo, Democratic Republic of the', flag: 'cd' },
  { code: '+682', country: 'Cook Islands', flag: 'ck' },
  { code: '+506', country: 'Costa Rica', flag: 'cr' },
  { code: '+385', country: 'Croatia', flag: 'hr' },
  { code: '+53', country: 'Cuba', flag: 'cu' },
  { code: '+599', country: 'Curaçao', flag: 'cw' },
  { code: '+357', country: 'Cyprus', flag: 'cy' },
  { code: '+420', country: 'Czech Republic', flag: 'cz' },
  { code: '+45', country: 'Denmark', flag: 'dk' },
  { code: '+253', country: 'Djibouti', flag: 'dj' },
  { code: '+1', country: 'Dominica', flag: 'dm' },
  { code: '+1', country: 'Dominican Republic', flag: 'do' },
  { code: '+670', country: 'East Timor (Timor-Leste)', flag: 'tl' },
  { code: '+56', country: 'Easter Island', flag: 'cl' },
  { code: '+593', country: 'Ecuador', flag: 'ec' },
  { code: '+20', country: 'Egypt', flag: 'eg' },
  { code: '+503', country: 'El Salvador', flag: 'sv' },
  { code: '+240', country: 'Equatorial Guinea', flag: 'gq' },
  { code: '+291', country: 'Eritrea', flag: 'er' },
  { code: '+372', country: 'Estonia', flag: 'ee' },
  { code: '+268', country: 'Eswatini', flag: 'sz' },
  { code: '+251', country: 'Ethiopia', flag: 'et' },
  { code: '+500', country: 'Falkland Islands', flag: 'fk' },
  { code: '+298', country: 'Faroe Islands', flag: 'fo' },
  { code: '+679', country: 'Fiji', flag: 'fj' },
  { code: '+358', country: 'Finland', flag: 'fi' },
  { code: '+33', country: 'France', flag: 'fr' },
  { code: '+241', country: 'Gabon', flag: 'ga' },
  { code: '+220', country: 'Gambia', flag: 'gm' },
  { code: '+995', country: 'Georgia', flag: 'ge' },
  { code: '+49', country: 'Germany', flag: 'de' },
  { code: '+233', country: 'Ghana', flag: 'gh' },
  { code: '+350', country: 'Gibraltar', flag: 'gi' },
  { code: '+30', country: 'Greece', flag: 'gr' },
  { code: '+299', country: 'Greenland', flag: 'gl' },
  { code: '+1', country: 'Grenada', flag: 'gd' },
  { code: '+590', country: 'Guadeloupe', flag: 'gp' },
  { code: '+1', country: 'Guam', flag: 'gu' },
  { code: '+502', country: 'Guatemala', flag: 'gt' },
  { code: '+44', country: 'Guernsey', flag: 'gg' },
  { code: '+224', country: 'Guinea', flag: 'gn' },
  { code: '+245', country: 'Guinea-Bissau', flag: 'gw' },
  { code: '+592', country: 'Guyana', flag: 'gy' },
  { code: '+509', country: 'Haiti', flag: 'ht' },
  { code: '+504', country: 'Honduras', flag: 'hn' },
  { code: '+852', country: 'Hong Kong', flag: 'hk' },
  { code: '+36', country: 'Hungary', flag: 'hu' },
  { code: '+354', country: 'Iceland', flag: 'is' },
  { code: '+91', country: 'India', flag: 'in' },
  { code: '+62', country: 'Indonesia', flag: 'id' },
  { code: '+870', country: 'Inmarsat SNAC', flag: 'satellite' },
  { code: '+98', country: 'Iran', flag: 'ir' },
  { code: '+964', country: 'Iraq', flag: 'iq' },
  { code: '+353', country: 'Ireland', flag: 'ie' },
  { code: '+44', country: 'Isle of Man', flag: 'im' },
  { code: '+972', country: 'Israel', flag: 'il' },
  { code: '+39', country: 'Italy', flag: 'it' },
  { code: '+225', country: "Ivory Coast (Côte d'Ivoire)", flag: 'ci' },
  { code: '+1', country: 'Jamaica', flag: 'jm' },
  { code: '+47', country: 'Jan Mayen', flag: 'sj' },
  { code: '+81', country: 'Japan', flag: 'jp' },
  { code: '+44', country: 'Jersey', flag: 'je' },
  { code: '+962', country: 'Jordan', flag: 'jo' },
  { code: '+7', country: 'Kazakhstan', flag: 'kz' },
  { code: '+254', country: 'Kenya', flag: 'ke' },
  { code: '+686', country: 'Kiribati', flag: 'ki' },
  { code: '+850', country: 'Korea, North', flag: 'kp' },
  { code: '+82', country: 'Korea, South', flag: 'kr' },
  { code: '+383', country: 'Kosovo', flag: 'xk' },
  { code: '+965', country: 'Kuwait', flag: 'kw' },
  { code: '+996', country: 'Kyrgyzstan', flag: 'kg' },
  { code: '+856', country: 'Laos', flag: 'la' },
  { code: '+371', country: 'Latvia', flag: 'lv' },
  { code: '+961', country: 'Lebanon', flag: 'lb' },
  { code: '+266', country: 'Lesotho', flag: 'ls' },
  { code: '+231', country: 'Liberia', flag: 'lr' },
  { code: '+218', country: 'Libya', flag: 'ly' },
  { code: '+423', country: 'Liechtenstein', flag: 'li' },
  { code: '+370', country: 'Lithuania', flag: 'lt' },
  { code: '+352', country: 'Luxembourg', flag: 'lu' },
  { code: '+853', country: 'Macau', flag: 'mo' },
  { code: '+261', country: 'Madagascar', flag: 'mg' },
  { code: '+265', country: 'Malawi', flag: 'mw' },
  { code: '+60', country: 'Malaysia', flag: 'my' },
  { code: '+960', country: 'Maldives', flag: 'mv' },
  { code: '+223', country: 'Mali', flag: 'ml' },
  { code: '+356', country: 'Malta', flag: 'mt' },
  { code: '+692', country: 'Marshall Islands', flag: 'mh' },
  { code: '+596', country: 'Martinique', flag: 'mq' },
  { code: '+222', country: 'Mauritania', flag: 'mr' },
  { code: '+230', country: 'Mauritius', flag: 'mu' },
  { code: '+262', country: 'Mayotte', flag: 'yt' },
  { code: '+52', country: 'Mexico', flag: 'mx' },
  { code: '+691', country: 'Micronesia, Federated States of', flag: 'fm' },
  { code: '+373', country: 'Moldova', flag: 'md' },
  { code: '+377', country: 'Monaco', flag: 'mc' },
  { code: '+976', country: 'Mongolia', flag: 'mn' },
  { code: '+382', country: 'Montenegro', flag: 'me' },
  { code: '+1', country: 'Montserrat', flag: 'ms' },
  { code: '+212', country: 'Morocco', flag: 'ma' },
  { code: '+258', country: 'Mozambique', flag: 'mz' },
  { code: '+95', country: 'Myanmar', flag: 'mm' },
  { code: '+264', country: 'Namibia', flag: 'na' },
  { code: '+674', country: 'Nauru', flag: 'nr' },
  { code: '+977', country: 'Nepal', flag: 'np' },
  { code: '+31', country: 'Netherlands', flag: 'nl' },
  { code: '+1', country: 'Nevis', flag: 'kn' },
  { code: '+687', country: 'New Caledonia', flag: 'nc' },
  { code: '+64', country: 'New Zealand', flag: 'nz' },
  { code: '+505', country: 'Nicaragua', flag: 'ni' },
  { code: '+227', country: 'Niger', flag: 'ne' },
  { code: '+234', country: 'Nigeria', flag: 'ng' },
  { code: '+683', country: 'Niue', flag: 'nu' },
  { code: '+672', country: 'Norfolk Island', flag: 'nf' },
  { code: '+389', country: 'North Macedonia', flag: 'mk' },
  { code: '+90', country: 'Northern Cyprus', flag: 'tr' },
  { code: '+44', country: 'Northern Ireland', flag: 'gb' },
  { code: '+1', country: 'Northern Mariana Islands', flag: 'mp' },
  { code: '+47', country: 'Norway', flag: 'no' },
  { code: '+968', country: 'Oman', flag: 'om' },
  { code: '+92', country: 'Pakistan', flag: 'pk' },
  { code: '+680', country: 'Palau', flag: 'pw' },
  { code: '+970', country: 'Palestine', flag: 'ps' },
  { code: '+507', country: 'Panama', flag: 'pa' },
  { code: '+675', country: 'Papua New Guinea', flag: 'pg' },
  { code: '+595', country: 'Paraguay', flag: 'py' },
  { code: '+51', country: 'Peru', flag: 'pe' },
  { code: '+63', country: 'Philippines', flag: 'ph' },
  { code: '+64', country: 'Pitcairn Islands', flag: 'pn' },
  { code: '+48', country: 'Poland', flag: 'pl' },
  { code: '+351', country: 'Portugal', flag: 'pt' },
  { code: '+1', country: 'Puerto Rico', flag: 'pr' },
  { code: '+974', country: 'Qatar', flag: 'qa' },
  { code: '+262', country: 'Réunion', flag: 're' },
  { code: '+40', country: 'Romania', flag: 'ro' },
  { code: '+7', country: 'Russia', flag: 'ru' },
  { code: '+250', country: 'Rwanda', flag: 'rw' },
  { code: '+599', country: 'Saba', flag: 'bq' },
  { code: '+590', country: 'Saint Barthélemy', flag: 'bl' },
  { code: '+290', country: 'Saint Helena', flag: 'sh' },
  { code: '+1', country: 'Saint Kitts and Nevis', flag: 'kn' },
  { code: '+1', country: 'Saint Lucia', flag: 'lc' },
  { code: '+590', country: 'Saint Martin (France)', flag: 'mf' },
  { code: '+508', country: 'Saint Pierre and Miquelon', flag: 'pm' },
  { code: '+1', country: 'Saint Vincent and the Grenadines', flag: 'vc' },
  { code: '+685', country: 'Samoa', flag: 'ws' },
  { code: '+378', country: 'San Marino', flag: 'sm' },
  { code: '+239', country: 'São Tomé and Príncipe', flag: 'st' },
  { code: '+966', country: 'Saudi Arabia', flag: 'sa' },
  { code: '+221', country: 'Senegal', flag: 'sn' },
  { code: '+381', country: 'Serbia', flag: 'rs' },
  { code: '+248', country: 'Seychelles', flag: 'sc' },
  { code: '+232', country: 'Sierra Leone', flag: 'sl' },
  { code: '+65', country: 'Singapore', flag: 'sg' },
  { code: '+599', country: 'Sint Eustatius', flag: 'bq' },
  { code: '+1', country: 'Sint Maarten (Netherlands)', flag: 'sx' },
  { code: '+421', country: 'Slovakia', flag: 'sk' },
  { code: '+386', country: 'Slovenia', flag: 'si' },
  { code: '+677', country: 'Solomon Islands', flag: 'sb' },
  { code: '+252', country: 'Somalia', flag: 'so' },
  { code: '+27', country: 'South Africa', flag: 'za' },
  {
    code: '+500',
    country: 'South Georgia and the South Sandwich Islands',
    flag: 'gs'
  },
  { code: '+211', country: 'South Sudan', flag: 'ss' },
  { code: '+34', country: 'Spain', flag: 'es' },
  { code: '+94', country: 'Sri Lanka', flag: 'lk' },
  { code: '+249', country: 'Sudan', flag: 'sd' },
  { code: '+597', country: 'Suriname', flag: 'sr' },
  { code: '+47', country: 'Svalbard', flag: 'sj' },
  { code: '+46', country: 'Sweden', flag: 'se' },
  { code: '+41', country: 'Switzerland', flag: 'ch' },
  { code: '+963', country: 'Syria', flag: 'sy' },
  { code: '+886', country: 'Taiwan', flag: 'tw' },
  { code: '+992', country: 'Tajikistan', flag: 'tj' },
  { code: '+255', country: 'Tanzania', flag: 'tz' },
  { code: '+66', country: 'Thailand', flag: 'th' },
  { code: '+228', country: 'Togo', flag: 'tg' },
  { code: '+690', country: 'Tokelau', flag: 'tk' },
  { code: '+676', country: 'Tonga', flag: 'to' },
  { code: '+373', country: 'Transnistria', flag: 'md' },
  { code: '+1', country: 'Trinidad and Tobago', flag: 'tt' },
  { code: '+290', country: 'Tristan da Cunha', flag: 'ta' },
  { code: '+216', country: 'Tunisia', flag: 'tn' },
  { code: '+90', country: 'Turkey', flag: 'tr' },
  { code: '+993', country: 'Turkmenistan', flag: 'tm' },
  { code: '+1', country: 'Turks and Caicos Islands', flag: 'tc' },
  { code: '+688', country: 'Tuvalu', flag: 'tv' },
  { code: '+256', country: 'Uganda', flag: 'ug' },
  { code: '+380', country: 'Ukraine', flag: 'ua' },
  { code: '+971', country: 'United Arab Emirates', flag: 'ae' },
  { code: '+44', country: 'United Kingdom', flag: 'gb' },
  { code: '+1', country: 'United States', flag: 'us' },
  { code: '+598', country: 'Uruguay', flag: 'uy' },
  { code: '+1', country: 'US Virgin Islands', flag: 'vi' },
  { code: '+998', country: 'Uzbekistan', flag: 'uz' },
  { code: '+678', country: 'Vanuatu', flag: 'vu' },
  { code: '+39', country: 'Vatican City State (Holy See)', flag: 'va' },
  { code: '+58', country: 'Venezuela', flag: 've' },
  { code: '+84', country: 'Vietnam', flag: 'vn' },
  { code: '+1', country: 'Wake Island, USA', flag: 'us' },
  { code: '+681', country: 'Wallis and Futuna', flag: 'wf' },
  { code: '+967', country: 'Yemen', flag: 'ye' },
  { code: '+260', country: 'Zambia', flag: 'zm' },
  { code: '+255', country: 'Zanzibar', flag: 'tz' },
  { code: '+263', country: 'Zimbabwe', flag: 'zw' }
];
